"""winget kataloğu: okul ve ofis bilgisayarları için seçilmiş paketler (Dağıtım → winget paketi).

Kimlikler microsoft/winget-pkgs deposunda doğrulandı (2026-10-05): her kimliğin klasöründe en yeni sürümün
<Kimlik>.installer.yaml dosyası var ve yalnızca kullanıcı kapsamında kurulan paket alınmadı (ajan --scope machine
ile SYSTEM olarak kurar). Ad ve yayıncı paketin varsayılan dil manifestinden. Katalogda olmayan bir paket de
kimliğiyle dağıtılabilir; bu liste yalnızca seçmeyi kolaylaştırır.

Veri Python modülündedir, JSON dosyasında değil: sunucuya kodu kuran pops-deploy-backend yalnızca Backend altındaki
.py dosyalarını, migration'ları, VERSION'ı ve anahtarı taşır.

Alanlar: id, name, publisher, category (pops/winget.py CATEGORY_LABELS), description (Türkçe), description_en;
isteğe bağlı note / note_en (lisans ya da kurulum uyarısı).
"""

UPDATED = "2026-10-05"
SOURCE = "https://github.com/microsoft/winget-pkgs"

PACKAGES = (
    # ── browser
    {"id": "Brave.Brave", "name": "Brave", "publisher": "Brave Software", "category": "browser",
     "description": "Reklam ve izleyici engelleyen web tarayıcısı.",
     "description_en": "Web browser that blocks ads and trackers."},
    {"id": "Google.Chrome", "name": "Google Chrome", "publisher": "Google", "category": "browser",
     "description": "Google'ın web tarayıcısı.", "description_en": "Web browser by Google."},
    {"id": "Mozilla.Firefox", "name": "Mozilla Firefox", "publisher": "Mozilla", "category": "browser",
     "description": "Açık kaynak web tarayıcısı.", "description_en": "Open-source web browser."},
    {"id": "Mozilla.Firefox.tr", "name": "Mozilla Firefox (Türkçe)", "publisher": "Mozilla", "category": "browser",
     "description": "Türkçe arayüzlü açık kaynak web tarayıcısı.",
     "description_en": "Open-source web browser with a Turkish interface."},
    {"id": "Opera.Opera", "name": "Opera", "publisher": "Opera Software", "category": "browser",
     "description": "Yerleşik reklam engelleyicili web tarayıcısı.",
     "description_en": "Web browser with a built-in ad blocker."},
    # ── office
    {"id": "Adobe.Acrobat.Reader.64-bit", "name": "Adobe Acrobat Reader", "publisher": "Adobe", "category": "office",
     "description": "PDF görüntüleme, yazdırma ve form doldurma aracı.",
     "description_en": "View, print and fill in PDF documents."},
    {"id": "calibre.calibre", "name": "calibre", "publisher": "Kovid Goyal", "category": "office",
     "description": "E-kitap yönetimi, dönüştürme ve okuma aracı.",
     "description_en": "E-book manager, converter and reader."},
    {"id": "JGraph.Draw", "name": "draw.io", "publisher": "JGraph", "category": "office",
     "description": "Şema ve diyagram çizim uygulaması.", "description_en": "Diagram and flowchart drawing app."},
    {"id": "TheDocumentFoundation.LibreOffice", "name": "LibreOffice", "publisher": "The Document Foundation",
     "category": "office", "description": "Açık kaynak ofis paketi: metin, hesap tablosu, sunum.",
     "description_en": "Open-source office suite for documents, spreadsheets and slides."},
    {"id": "Mozilla.Thunderbird", "name": "Mozilla Thunderbird", "publisher": "Mozilla", "category": "office",
     "description": "E-posta, takvim ve kişi yönetimi uygulaması.",
     "description_en": "Email, calendar and contacts app."},
    {"id": "Notepad++.Notepad++", "name": "Notepad++", "publisher": "Notepad++ Team", "category": "office",
     "description": "Kaynak kod için gelişmiş metin düzenleyici.",
     "description_en": "Advanced text and source code editor."},
    {"id": "ONLYOFFICE.DesktopEditors", "name": "ONLYOFFICE Desktop Editors", "publisher": "Ascensio System",
     "category": "office", "description": "Microsoft Office biçimleriyle uyumlu ofis paketi.",
     "description_en": "Office suite compatible with Microsoft Office formats."},
    {"id": "PDFsam.PDFsam", "name": "PDFsam Basic", "publisher": "Sober Lemur", "category": "office",
     "description": "PDF dosyalarını birleştirme ve bölme aracı.", "description_en": "Merge and split PDF files."},
    {"id": "SumatraPDF.SumatraPDF", "name": "SumatraPDF", "publisher": "Krzysztof Kowalczyk", "category": "office",
     "description": "Hafif PDF, EPUB ve DjVu okuyucu.", "description_en": "Lightweight PDF, EPUB and DjVu reader."},
    {"id": "DigitalScholar.Zotero", "name": "Zotero", "publisher": "Corporation for Digital Scholarship",
     "category": "office", "description": "Kaynakça ve atıf yönetimi aracı.",
     "description_en": "Reference and citation manager."},
    # ── education
    {"id": "Avogadro.Avogadro.2", "name": "Avogadro 2", "publisher": "avogadro.cc", "category": "education",
     "description": "Molekül modelleme ve görselleştirme yazılımı.",
     "description_en": "Molecule modeling and visualization software."},
    {"id": "Celestia.Celestia", "name": "Celestia", "publisher": "Celestia Development Team", "category": "education",
     "description": "Evreni üç boyutlu keşfetmeyi sağlayan uzay simülasyonu.",
     "description_en": "3D space simulation for exploring the universe."},
    {"id": "KDE.GCompris", "name": "GCompris", "publisher": "GCompris team", "category": "education",
     "description": "2-10 yaş arası çocuklar için eğitsel etkinlikler.",
     "description_en": "Educational activities for children aged 2 to 10."},
    {"id": "GeoGebra.Classic", "name": "GeoGebra Classic", "publisher": "International GeoGebra Institute",
     "category": "education", "description": "Dinamik geometri ve matematik yazılımı.",
     "description_en": "Dynamic geometry and mathematics software."},
    {"id": "KDE.Marble", "name": "Marble", "publisher": "KDE", "category": "education",
     "description": "Sanal küre ve dünya atlası.", "description_en": "Virtual globe and world atlas."},
    {"id": "Musescore.Musescore", "name": "MuseScore", "publisher": "MuseScore", "category": "education",
     "description": "Nota yazma ve müzik notasyonu programı.",
     "description_en": "Music notation and score writing software."},
    {"id": "MITMediaLab.Scratch.3", "name": "Scratch 3", "publisher": "Scratch Foundation", "category": "education",
     "description": "Blok tabanlı programlama ile kodlama eğitimi.",
     "description_en": "Learn coding with block-based programming."},
    {"id": "Stellarium.Stellarium", "name": "Stellarium", "publisher": "Stellarium team", "category": "education",
     "description": "Gerçekçi gökyüzü gösteren planetaryum yazılımı.",
     "description_en": "Planetarium software that shows a realistic sky."},
    {"id": "NewBreedSoftware.TuxPaint", "name": "Tux Paint", "publisher": "New Breed Software",
     "category": "education", "description": "Çocuklar için çizim ve boyama programı.",
     "description_en": "Drawing and painting program for children."},
    # ── programming
    {"id": "ArduinoSA.IDE.stable", "name": "Arduino IDE", "publisher": "Arduino", "category": "programming",
     "description": "Arduino kartları için kod yazma ve yükleme ortamı.",
     "description_en": "Write and upload code to Arduino boards."},
    {"id": "CodeBlocks.CodeBlocks", "name": "Code::Blocks", "publisher": "The Code::Blocks Team",
     "category": "programming", "description": "C ve C++ için geliştirme ortamı.",
     "description_en": "Development environment for C and C++."},
    {"id": "EclipseAdoptium.Temurin.21.JDK", "name": "Eclipse Temurin JDK 21", "publisher": "Eclipse Adoptium",
     "category": "programming", "description": "Java 21 geliştirme kiti (OpenJDK).",
     "description_en": "Java 21 development kit (OpenJDK)."},
    {"id": "Git.Git", "name": "Git", "publisher": "The Git Development Community", "category": "programming",
     "description": "Dağıtık sürüm kontrol sistemi.", "description_en": "Distributed version control system."},
    {"id": "GitHub.GitHubDesktop", "name": "GitHub Desktop", "publisher": "GitHub", "category": "programming",
     "description": "Git depolarını görsel arayüzle yönetme aracı.",
     "description_en": "Manage Git repositories with a graphical interface."},
    {"id": "Lazarus.Lazarus", "name": "Lazarus", "publisher": "Lazarus Team", "category": "programming",
     "description": "Free Pascal için görsel geliştirme ortamı.",
     "description_en": "Visual development environment for Free Pascal."},
    {"id": "OpenJS.NodeJS.LTS", "name": "Node.js LTS", "publisher": "Node.js Foundation", "category": "programming",
     "description": "JavaScript çalışma ortamı, uzun süreli destek sürümü.",
     "description_en": "JavaScript runtime, long-term support release."},
    {"id": "Microsoft.PowerShell", "name": "PowerShell", "publisher": "Microsoft", "category": "programming",
     "description": "Komut satırı kabuğu ve betik dili.",
     "description_en": "Command-line shell and scripting language."},
    {"id": "JetBrains.PyCharm", "name": "PyCharm", "publisher": "JetBrains", "category": "programming",
     "description": "Python için geliştirme ortamı (IDE).",
     "description_en": "Development environment (IDE) for Python.",
     "note": "Temel özellikler ücretsiz; Pro özellikleri abonelik ister.",
     "note_en": "Core features are free; Pro features need a subscription."},
    {"id": "Python.Python.3.12", "name": "Python 3.12", "publisher": "Python Software Foundation",
     "category": "programming", "description": "Python 3.12 programlama dili.",
     "description_en": "Python 3.12 programming language."},
    {"id": "Python.Python.3.13", "name": "Python 3.13", "publisher": "Python Software Foundation",
     "category": "programming", "description": "Python 3.13 programlama dili.",
     "description_en": "Python 3.13 programming language."},
    {"id": "AivarAnnamaa.Thonny", "name": "Thonny", "publisher": "Aivar Annamaa", "category": "programming",
     "description": "Yeni başlayanlar için Python geliştirme ortamı.",
     "description_en": "Python development environment for beginners."},
    {"id": "Microsoft.VisualStudioCode", "name": "Visual Studio Code", "publisher": "Microsoft",
     "category": "programming", "description": "Eklentilerle genişletilebilen kod düzenleyici.",
     "description_en": "Extensible source code editor."},
    # ── graphics
    {"id": "BlenderFoundation.Blender", "name": "Blender", "publisher": "Blender Foundation", "category": "graphics",
     "description": "3B modelleme, animasyon ve görüntü oluşturma yazılımı.",
     "description_en": "3D modeling, animation and rendering software."},
    {"id": "FreeCAD.FreeCAD", "name": "FreeCAD", "publisher": "FreeCAD Team", "category": "graphics",
     "description": "Parametrik 3B CAD modelleme yazılımı.", "description_en": "Parametric 3D CAD modeling software."},
    {"id": "GIMP.GIMP.3", "name": "GIMP", "publisher": "The GIMP Team", "category": "graphics",
     "description": "Açık kaynak resim düzenleme programı.", "description_en": "Open-source image editor."},
    {"id": "Greenshot.Greenshot", "name": "Greenshot", "publisher": "Greenshot", "category": "graphics",
     "description": "Ekran görüntüsü alma ve işaretleme aracı.",
     "description_en": "Screenshot capture and annotation tool."},
    {"id": "Inkscape.Inkscape", "name": "Inkscape", "publisher": "Inkscape", "category": "graphics",
     "description": "Vektör grafik çizim programı.", "description_en": "Vector graphics editor."},
    {"id": "IrfanSkiljan.IrfanView", "name": "IrfanView", "publisher": "Irfan Skiljan", "category": "graphics",
     "description": "Hızlı resim görüntüleyici ve dönüştürücü.", "description_en": "Fast image viewer and converter."},
    {"id": "KDE.Krita", "name": "Krita", "publisher": "Krita Foundation", "category": "graphics",
     "description": "Dijital boyama ve illüstrasyon programı.",
     "description_en": "Digital painting and illustration program."},
    {"id": "dotPDN.PaintDotNet", "name": "paint.net", "publisher": "dotPDN", "category": "graphics",
     "description": "Kolay kullanımlı resim düzenleme programı.", "description_en": "Easy-to-use image editor."},
    {"id": "ShareX.ShareX", "name": "ShareX", "publisher": "ShareX Team", "category": "graphics",
     "description": "Ekran görüntüsü ve ekran kaydı aracı.", "description_en": "Screenshot and screen recording tool."},
    # ── media
    {"id": "Audacity.Audacity", "name": "Audacity", "publisher": "Audacity", "category": "media",
     "description": "Ses kaydı ve düzenleme programı.", "description_en": "Audio recording and editing program."},
    {"id": "HandBrake.HandBrake", "name": "HandBrake", "publisher": "The HandBrake Team", "category": "media",
     "description": "Video dönüştürme ve sıkıştırma aracı.",
     "description_en": "Video conversion and compression tool."},
    {"id": "KDE.Kdenlive", "name": "Kdenlive", "publisher": "KDE", "category": "media",
     "description": "Açık kaynak video düzenleme programı.", "description_en": "Open-source video editor."},
    {"id": "LMMS.LMMS", "name": "LMMS", "publisher": "LMMS Developers", "category": "media",
     "description": "Müzik üretimi ve beste yazılımı.", "description_en": "Music production and composition software."},
    {"id": "OBSProject.OBSStudio", "name": "OBS Studio", "publisher": "OBS Project", "category": "media",
     "description": "Ekran kaydı ve canlı yayın yazılımı.",
     "description_en": "Screen recording and live streaming software."},
    {"id": "Meltytech.Shotcut", "name": "Shotcut", "publisher": "Meltytech", "category": "media",
     "description": "Ücretsiz video düzenleme programı.", "description_en": "Free video editor."},
    {"id": "VideoLAN.VLC", "name": "VLC media player", "publisher": "VideoLAN", "category": "media",
     "description": "Hemen her biçimi oynatabilen medya oynatıcı.",
     "description_en": "Media player that plays almost any format."},
    # ── communication
    {"id": "Microsoft.Teams", "name": "Microsoft Teams", "publisher": "Microsoft", "category": "communication",
     "description": "Sohbet, toplantı ve iş birliği uygulaması.",
     "description_en": "Chat, meetings and collaboration app.",
     "note": "MSIX paketi: önce tek bir bilgisayarda deneyin.",
     "note_en": "MSIX package: try it on one computer first."},
    {"id": "Cisco.Webex", "name": "Webex", "publisher": "Cisco", "category": "communication",
     "description": "Görüntülü toplantı ve iş birliği uygulaması.",
     "description_en": "Video meetings and collaboration app."},
    {"id": "Zoom.Zoom", "name": "Zoom Workplace", "publisher": "Zoom", "category": "communication",
     "description": "Görüntülü görüşme ve çevrim içi toplantı uygulaması.",
     "description_en": "Video calls and online meetings app."},
    # ── utility
    {"id": "7zip.7zip", "name": "7-Zip", "publisher": "Igor Pavlov", "category": "utility",
     "description": "Dosya sıkıştırma ve arşiv açma aracı.", "description_en": "File compression and archive tool."},
    {"id": "CPUID.CPU-Z", "name": "CPU-Z", "publisher": "CPUID", "category": "utility",
     "description": "İşlemci, bellek ve anakart bilgilerini gösterir.",
     "description_en": "Shows CPU, memory and motherboard details."},
    {"id": "CrystalDewWorld.CrystalDiskInfo", "name": "CrystalDiskInfo", "publisher": "Crystal Dew World",
     "category": "utility", "description": "Disk sağlığını ve S.M.A.R.T. verilerini izler.",
     "description_en": "Monitors disk health and S.M.A.R.T. data."},
    {"id": "voidtools.Everything", "name": "Everything", "publisher": "voidtools", "category": "utility",
     "description": "Dosya ve klasörleri anında bulan arama aracı.",
     "description_en": "Instant file and folder search tool."},
    {"id": "KeePassXCTeam.KeePassXC", "name": "KeePassXC", "publisher": "KeePassXC Team", "category": "utility",
     "description": "Çevrim dışı parola yöneticisi.", "description_en": "Offline password manager."},
    {"id": "Oracle.VirtualBox", "name": "Oracle VirtualBox", "publisher": "Oracle", "category": "utility",
     "description": "Sanal makine oluşturma ve çalıştırma yazılımı.",
     "description_en": "Create and run virtual machines."},
    {"id": "Microsoft.PowerToys", "name": "PowerToys", "publisher": "Microsoft", "category": "utility",
     "description": "Windows için ek araçlar ve kısayollar.",
     "description_en": "Extra tools and shortcuts for Windows."},
    {"id": "PuTTY.PuTTY", "name": "PuTTY", "publisher": "Simon Tatham", "category": "utility",
     "description": "SSH ve Telnet istemcisi.", "description_en": "SSH and Telnet client."},
    {"id": "RARLab.WinRAR", "name": "WinRAR", "publisher": "win.rar", "category": "utility",
     "description": "RAR ve ZIP arşiv yöneticisi.", "description_en": "RAR and ZIP archive manager.",
     "note": "Deneme sürümüdür; kurumlarda bilgisayar başına lisans gerekir.",
     "note_en": "Shareware; organisations need a licence per computer."},
    {"id": "WinSCP.WinSCP", "name": "WinSCP", "publisher": "Martin Prikryl", "category": "utility",
     "description": "SFTP, FTP ve SCP dosya aktarım istemcisi.",
     "description_en": "SFTP, FTP and SCP file transfer client."},
    {"id": "WiresharkFoundation.Wireshark", "name": "Wireshark", "publisher": "The Wireshark developer community",
     "category": "utility", "description": "Ağ trafiği yakalama ve inceleme aracı.",
     "description_en": "Network traffic capture and analysis tool."},
    # ── runtime
    {"id": "Microsoft.DotNet.DesktopRuntime.8", "name": "Microsoft .NET Windows Desktop Runtime 8",
     "publisher": "Microsoft", "category": "runtime",
     "description": ".NET 8 masaüstü uygulamaları için çalışma ortamı.",
     "description_en": "Runtime for .NET 8 desktop applications."},
    {"id": "Microsoft.VCRedist.2015+.x64", "name": "Microsoft Visual C++ v14 Redistributable (x64)",
     "publisher": "Microsoft", "category": "runtime",
     "description": "Birçok programın ihtiyaç duyduğu C++ kitaplıkları.",
     "description_en": "C++ runtime libraries required by many programs."},
)
